name: 01 - Building Blocks
on:
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      -run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      -run: | 
      echo "I am"
      echo "a multi line"
      echo "script"
    