name: 02 - Building Blocks

on:
  workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
        - name: Event name
          run: |
            echo "Event name: ${{ github.event_name }}"
